services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: wallet-challenge-api
        depends_on:
            - dbwallet
            - redis
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        command: php -S 0.0.0.0:8000 -t /var/www/public
        networks:
            - default-network
        deploy:
            resources:
                limits:
                    cpus: "3.50"
                    memory: 1024M

    dbwallet:
        container_name: dbwallet
        hostname: dbwallet
        image: mysql:8.0
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: walletdatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mydata:/var/lib/mysql
        networks:
            - default-network
        deploy:
            resources:
                limits:
                    cpus: "2.00"
                    memory: 2048M

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        networks:
            - default-network
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 100M

networks:
    default-network:

volumes:
    mydata:
        driver: local
